# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from main import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(451, 437)
        MainWindow.setStyleSheet("background:qlineargradient(spread:pad, x1:0.339, y1:0.595727, x2:0.938, y2:0.096, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.first = QtWidgets.QComboBox(self.centralwidget)
        self.first.setGeometry(QtCore.QRect(150, 80, 141, 31))
        self.first.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.first.setObjectName("first")
        self.first.addItem("USD")
        self.first.addItem("RUB")
        self.first.addItem("EURO")
        self.first.addItem("CNY")
        self.second = QtWidgets.QComboBox(self.centralwidget)
        self.second.setGeometry(QtCore.QRect(150, 200, 141, 31))
        self.second.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.second.setObjectName("second")
        self.second.addItem("USD")
        self.second.addItem("RUB")
        self.second.addItem("EURO")
        self.second.addItem("CNY")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(150, 320, 141, 31))
        self.result.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.result.setObjectName("result")

        self.currency = QtWidgets.QLineEdit(self.centralwidget)
        self.currency.setGeometry(QtCore.QRect(150, 140, 141, 31))
        self.currency.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.currency.setObjectName("currency")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sum = QtWidgets.QPushButton(self.centralwidget)
        self.sum.setGeometry(QtCore.QRect(150, 260, 141, 31))
        self.sum.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.sum.setObjectName("sum")
        def generate():
            summ = str(clicked_on(self))
            return self.result.setText(summ)
        
        self.sum.clicked.connect(generate)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "конвертер валют"))
        self.first.setItemText(0, _translate("MainWindow", "USD"))
        self.first.setItemText(1, _translate("MainWindow", "RUB"))
        self.first.setItemText(2, _translate("MainWindow", "EURO"))
        self.first.setItemText(3, _translate("MainWindow", "CNY"))
        self.second.setItemText(0, _translate("MainWindow", "USD"))
        self.second.setItemText(1, _translate("MainWindow", "RUB"))
        self.second.setItemText(2, _translate("MainWindow", "EURO"))
        self.second.setItemText(3, _translate("MainWindow", "CNY"))
        self.sum.setText(_translate("MainWindow", "Вычислить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
